# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Organon < Formula
  desc "Structure-aware tools for AI agents"
  homepage "https://github.com/tta-lab/organon"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tta-lab/organon/releases/download/v1.0.0/organon_Darwin_x86_64.tar.gz"
      sha256 "733d12041e5291d15abae5cb173b5dfb2fa5ee2c3f88018b5bcb8c35314d454e"

      define_method(:install) do
        bin.install "src"
        bin.install "web"
        bin.install "skill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tta-lab/organon/releases/download/v1.0.0/organon_Darwin_arm64.tar.gz"
      sha256 "3c90f0d336bbdfcd3aab7414987abf7632eb68da385f0d6a7a437ea3fbd0e1d7"

      define_method(:install) do
        bin.install "src"
        bin.install "web"
        bin.install "skill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tta-lab/organon/releases/download/v1.0.0/organon_Linux_x86_64.tar.gz"
      sha256 "259b1a59c47c1f7c4123337e97d19a5934a2cd5ac093c74ed566270bfe6ec275"
      define_method(:install) do
        bin.install "src"
        bin.install "web"
        bin.install "skill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tta-lab/organon/releases/download/v1.0.0/organon_Linux_arm64.tar.gz"
      sha256 "271767ddf3bdb2203f668a8aa6ef2e65ca1c0793a6ee5f59b29bc7d2f7d0c3fe"
      define_method(:install) do
        bin.install "src"
        bin.install "web"
        bin.install "skill"
      end
    end
  end

  test do
    system "#{bin}/src", "--help"
    system "#{bin}/web", "--help"
    system "#{bin}/skill", "--help"
  end
end
