# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Organon < Formula
  desc "Structure-aware tools for AI agents"
  homepage "https://github.com/tta-lab/organon"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tta-lab/organon/releases/download/v0.1.0/organon_Darwin_x86_64.tar.gz"
      sha256 "3b5d660463389b6b2a22f723c6b4862f5d37b8977aab9625b3f959d929db140c"

      define_method(:install) do
        bin.install "src"
        bin.install "web"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tta-lab/organon/releases/download/v0.1.0/organon_Darwin_arm64.tar.gz"
      sha256 "380bd389b24c95d3a47a29d172a41a5a3ba986f46879086363d69125afba6203"

      define_method(:install) do
        bin.install "src"
        bin.install "web"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tta-lab/organon/releases/download/v0.1.0/organon_Linux_x86_64.tar.gz"
      sha256 "61ed5ecd481bd906461c52bf9bc35782314c5e6672a0cae696e272b80c378de7"
      define_method(:install) do
        bin.install "src"
        bin.install "web"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tta-lab/organon/releases/download/v0.1.0/organon_Linux_arm64.tar.gz"
      sha256 "af9d225e337c27244fc8e9ea2b168a74203428b751f9440efca7a4ea0ba48c04"
      define_method(:install) do
        bin.install "src"
        bin.install "web"
      end
    end
  end

  test do
    system "#{bin}/src", "--help"
    system "#{bin}/web", "--help"
  end
end
