# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Temenos < Formula
  desc "Sandbox daemon for AI agents — filesystem isolation via seatbelt and bubblewrap"
  homepage "https://github.com/tta-lab/temenos"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tta-lab/temenos/releases/download/v0.1.9/temenos_Darwin_x86_64.tar.gz"
      sha256 "72f70a1deb962dcbbcd91828fbe622346e55c131fc311ec1764b34877d7df942"

      define_method(:install) do
        bin.install "temenos"
        generate_completions_from_executable(bin/"temenos", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tta-lab/temenos/releases/download/v0.1.9/temenos_Darwin_arm64.tar.gz"
      sha256 "5a40c8862caa000cf53725da0877106d84deba3ccead2abcd39b78952262f9b8"

      define_method(:install) do
        bin.install "temenos"
        generate_completions_from_executable(bin/"temenos", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tta-lab/temenos/releases/download/v0.1.9/temenos_Linux_x86_64.tar.gz"
      sha256 "7dc068cb3ead328230a297c06c020a48454a39fccb5b97e51b6b224424fc2c9c"
      define_method(:install) do
        bin.install "temenos"
        generate_completions_from_executable(bin/"temenos", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tta-lab/temenos/releases/download/v0.1.9/temenos_Linux_arm64.tar.gz"
      sha256 "65d5e808bf5fe5a2b77fc5ac1391b5d1233633fdbbc619a9b4784f9efbf07766"
      define_method(:install) do
        bin.install "temenos"
        generate_completions_from_executable(bin/"temenos", "completion")
      end
    end
  end

  test do
    system "#{bin}/temenos", "version"
  end
end
