# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Temenos < Formula
  desc "Sandbox daemon for AI agents — filesystem isolation via seatbelt and bubblewrap"
  homepage "https://github.com/tta-lab/temenos"
  version "1.4.5+0.74.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tta-lab/temenos/releases/download/v1.4.5+0.74.1/temenos_Darwin_x86_64.tar.gz"
      sha256 "1cb158255cfdd94388d03f29a4a0be8d4234c784f671b88ed4b5fc7cc9804e88"

      define_method(:install) do
        bin.install "temenos"
        generate_completions_from_executable(bin/"temenos", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tta-lab/temenos/releases/download/v1.4.5+0.74.1/temenos_Darwin_arm64.tar.gz"
      sha256 "0c649cfdbfefc90c597e26b87f14bbb786f31c1c55b0b06f5ec62665b662f036"

      define_method(:install) do
        bin.install "temenos"
        generate_completions_from_executable(bin/"temenos", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tta-lab/temenos/releases/download/v1.4.5+0.74.1/temenos_Linux_x86_64.tar.gz"
      sha256 "5751d7a2d2d22286f2143959dc501329002e99e34ab5bce3b3df64e06a320b7b"
      define_method(:install) do
        bin.install "temenos"
        generate_completions_from_executable(bin/"temenos", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tta-lab/temenos/releases/download/v1.4.5+0.74.1/temenos_Linux_arm64.tar.gz"
      sha256 "927ea6ce442ca8d7a8e51af6e43f1fb906b495ee493e4ed5ffb10be9db04e003"
      define_method(:install) do
        bin.install "temenos"
        generate_completions_from_executable(bin/"temenos", "completion")
      end
    end
  end

  test do
    system "#{bin}/temenos", "version"
  end
end
