# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ttal < Formula
  desc "Agent infrastructure CLI - manage tasks, send messages, coordinate agents"
  homepage "https://github.com/tta-lab/ttal-cli"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tta-lab/ttal-cli/releases/download/v1.3.0/ttal_Darwin_x86_64.tar.gz"
      sha256 "7f6270857289e2ac6443a24ad61df2861e036c6065873cb91264f6174a3918d0"

      define_method(:install) do
        bin.install "ttal"

        generate_completions_from_executable(bin/"ttal", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tta-lab/ttal-cli/releases/download/v1.3.0/ttal_Darwin_arm64.tar.gz"
      sha256 "9a5fee2e81ad6ddab92b307740b7c24cfb4c4140466d4fd37fca2a1b63d720ad"

      define_method(:install) do
        bin.install "ttal"

        generate_completions_from_executable(bin/"ttal", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tta-lab/ttal-cli/releases/download/v1.3.0/ttal_Linux_x86_64.tar.gz"
      sha256 "a6d5010e7ae799b3d7f7f780a34b0f281f98976f6a48e9145bb3cedb2cbdcfd2"
      define_method(:install) do
        bin.install "ttal"

        generate_completions_from_executable(bin/"ttal", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tta-lab/ttal-cli/releases/download/v1.3.0/ttal_Linux_arm64.tar.gz"
      sha256 "c1c15e96b7c2608b5d2a6629ee8b9811c6002a3a695341ca1e3680e5e795d1ec"
      define_method(:install) do
        bin.install "ttal"

        generate_completions_from_executable(bin/"ttal", "completion")
      end
    end
  end

  test do
    system "#{bin}/ttal", "version"
  end
end
