# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ttal < Formula
  desc "Agent infrastructure CLI - manage tasks, send messages, coordinate agents"
  homepage "https://github.com/tta-lab/ttal-cli"
  version "1.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tta-lab/ttal-cli/releases/download/v1.7.1/ttal_Darwin_x86_64.tar.gz"
      sha256 "6255f55db0f3147416ccbc1b6f6c5a61659183b3f2f42d6a1dfa0bba1144d5b1"

      define_method(:install) do
        bin.install "ttal"

        generate_completions_from_executable(bin/"ttal", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tta-lab/ttal-cli/releases/download/v1.7.1/ttal_Darwin_arm64.tar.gz"
      sha256 "5586a991c6a3c663ffed7526b664600c38f60d6a596338716ab8c9ade36ae82b"

      define_method(:install) do
        bin.install "ttal"

        generate_completions_from_executable(bin/"ttal", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tta-lab/ttal-cli/releases/download/v1.7.1/ttal_Linux_x86_64.tar.gz"
      sha256 "6cbf7258ae5dc2f4c2d586934207ccc1ae37d6163123523a595465bdb4bcdfd0"
      define_method(:install) do
        bin.install "ttal"

        generate_completions_from_executable(bin/"ttal", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tta-lab/ttal-cli/releases/download/v1.7.1/ttal_Linux_arm64.tar.gz"
      sha256 "8ae0d04b725d171fd4ad8651c09523f87624ad07b1b723bab4d43dda67c7357b"
      define_method(:install) do
        bin.install "ttal"

        generate_completions_from_executable(bin/"ttal", "completion")
      end
    end
  end

  test do
    system "#{bin}/ttal", "version"
  end
end
